version: '3.1'

services:

  wordpress:
    container_name: wordpress
    image: wordpress
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_PASSWORD: 8fop4hnTwPwgSWEllVzn

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 8fop4hnTwPwgSWEllVzn
